### ISSUE TITLE
Adding ublas bindings to StarSpace

### ISSUE THREAD

**Issue by rnditdev** [inducer/pyublas#6]
Hello and sorry for this probable crosspost of an issue.

There are efforts for building Python bindings for the StarSpace NLP model, and the only remaining part is a binding of ublas matrix_row. Any idea about how we can apply this unique binding from your work to the project?

Thanks!

Ref:
https://github.com/facebookresearch/StarSpace/pull/197

**Comment by inducer** [comment]
Sorry, not sure I can be of help with this. You're welcome to any of the code in the repo. Beyond that, I'm not really using pyublas myself any more--sorry.
